// config/roles.js
/**
 * Role definitions and permissions configuration
 */

// Define user roles
const ROLES = {
  ADMIN: "admin",
  SUPERVISOR: "supervisor",
  ASSESSOR: "assessor",
  PARTICIPANT: "participant",
};

// Define permissions and which roles have them
const PERMISSIONS = {
  // Assessment permissions
  CREATE_ASSESSMENT: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.ASSESSOR],
  VIEW_OWN_ASSESSMENTS: [
    ROLES.ADMIN,
    ROLES.SUPERVISOR,
    ROLES.ASSESSOR,
    ROLES.PARTICIPANT,
  ],
  VIEW_ALL_ASSESSMENTS: [ROLES.ADMIN, ROLES.SUPERVISOR],
  UPDATE_OWN_ASSESSMENTS: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.ASSESSOR],
  UPDATE_ANY_ASSESSMENT: [ROLES.ADMIN, ROLES.SUPERVISOR],
  DELETE_OWN_ASSESSMENTS: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.ASSESSOR],
  DELETE_ANY_ASSESSMENT: [ROLES.ADMIN],
  TAKE_ASSESSMENT: [ROLES.PARTICIPANT],

  // User management permissions
  VIEW_USERS: [ROLES.ADMIN, ROLES.SUPERVISOR],
  CREATE_USER: [ROLES.ADMIN],
  UPDATE_USER: [ROLES.ADMIN],
  DELETE_USER: [ROLES.ADMIN],
  CHANGE_USER_ROLE: [ROLES.ADMIN],

  // Assignment permissions
  CREATE_ASSIGNMENT: [ROLES.ADMIN, ROLES.SUPERVISOR],
  VIEW_OWN_ASSIGNMENTS: [
    ROLES.ADMIN,
    ROLES.SUPERVISOR,
    ROLES.ASSESSOR,
    ROLES.PARTICIPANT,
  ],
  VIEW_ALL_ASSIGNMENTS: [ROLES.ADMIN, ROLES.SUPERVISOR],
  UPDATE_ASSIGNMENT: [ROLES.ADMIN, ROLES.SUPERVISOR],
  DELETE_ASSIGNMENT: [ROLES.ADMIN, ROLES.SUPERVISOR],

  // Report permissions
  GENERATE_REPORTS: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.ASSESSOR],
  VIEW_STATISTICS: [ROLES.ADMIN, ROLES.SUPERVISOR],
  EXPORT_DATA: [ROLES.ADMIN, ROLES.SUPERVISOR],

  // Section and question management
  MANAGE_SECTIONS: [ROLES.ADMIN, ROLES.SUPERVISOR],
  MANAGE_QUESTIONS: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.ASSESSOR],
};

module.exports = {
  ROLES,
  PERMISSIONS,
};
