// config/roles.js
/**
 * Role definitions and permissions configuration
 */

// Define user roles
const ROLES = {
  ADMIN: "admin",
  SUPERVISOR: "supervisor",
  ASSESSOR: "assessor",
};

// Define permissions and which roles have them
const PERMISSIONS = {
  // Assessment permissions
  CREATE_ASSESSMENT: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.ASSESSOR],
  VIEW_OWN_ASSESSMENTS: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.ASSESSOR],
  VIEW_ALL_ASSESSMENTS: [ROLES.ADMIN, ROLES.SUPERVISOR],
  UPDATE_OWN_ASSESSMENTS: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.ASSESSOR],
  UPDATE_ANY_ASSESSMENT: [ROLES.ADMIN, ROLES.SUPERVISOR],
  DELETE_OWN_ASSESSMENTS: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.ASSESSOR],
  DELETE_ANY_ASSESSMENT: [ROLES.ADMIN],

  // User management permissions
  VIEW_USERS: [ROLES.ADMIN, ROLES.SUPERVISOR],
  CREATE_USER: [ROLES.ADMIN],
  UPDATE_USER: [ROLES.ADMIN],
  DELETE_USER: [ROLES.ADMIN],
  CHANGE_USER_ROLE: [ROLES.ADMIN],

  // Report permissions
  GENERATE_REPORTS: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.ASSESSOR],
  VIEW_STATISTICS: [ROLES.ADMIN, ROLES.SUPERVISOR],
  EXPORT_DATA: [ROLES.ADMIN, ROLES.SUPERVISOR],
};

module.exports = {
  ROLES,
  PERMISSIONS,
};
